import type { Place } from '../src/domain/types';
import type { RawPlace } from '../src/domain/normalize/raw';
import { formatMinutes } from '../src/lib/time';

export function buildAudit(raws: RawPlace[], places: Place[]): string {
  const rawById = new Map(raws.map((r) => [r.id, r]));
  return [
    '# Data normalization audit',
    '',
    '_Generated by `npm run normalize`. Do not edit by hand._',
    '',
    summary(places),
    section('Hours unverified (null in source — schedulable only 10:00–18:00, badged in UI)', places, 'hours-unverified', (p) => `type \`${p.type}\` has no hours in source`),
    section('Hours approximated (vague text mapped to a coarse window)', places, 'hours-approximated', (p) => `"${rawById.get(p.id)?.hours}" → ${describeWeekly(p)}`),
    section('Hours unparsed (parser gave up — should be empty)', places, 'hours-unparsed', (p) => `"${rawById.get(p.id)?.hours}"`),
    section('Duration estimated (null in source → per-type median)', places, 'duration-estimated', (p) => `null → ${p.visitMinutes} min (median for \`${p.type}\`)`),
    section('Booking unknown (null in source — shown as "check ahead")', places, 'booking-unknown', () => 'null preserved'),
    section('Suspect coordinates (>30 km from city centroid — excluded from map and travel math)', places, 'coords-suspect', (p) => `[${p.coords.lat}, ${p.coords.lon}] far from ${p.city}`),
    section('Aliases (same location + same name modulo city qualifiers — hidden from catalog)', places, 'alias', (p) => `alias of \`${p.aliasOf}\``),
    seasonalSection(places),
  ].join('\n');
}

function summary(places: Place[]): string {
  const kinds = { exact: 0, inferred: 0, openAccess: 0, unknown: 0 };
  for (const p of places) {
    if (p.hours.kind === 'weekly') kinds[p.hours.source] += 1;
    else kinds[p.hours.kind] += 1;
  }
  return [
    '## Summary',
    '',
    `- ${places.length} places normalized`,
    `- Hours: ${kinds.exact} parsed exactly, ${kinds.inferred} inferred from vague text, ${kinds.openAccess} open-access (neighborhoods), ${kinds.unknown} honestly unknown`,
    `- Principle: unknowns stay unknown; defaults exist only where scheduling needs a number, and every one is flagged below and surfaced in the UI.`,
    '',
  ].join('\n');
}

function section(
  title: string,
  places: Place[],
  flag: Place['flags'][number],
  decision: (p: Place) => string
): string {
  const rows = places.filter((p) => p.flags.includes(flag));
  const header = `## ${title}\n\n${rows.length} place(s).`;
  if (rows.length === 0) return `${header}\n`;
  const table = rows.map((p) => `| ${p.id} | ${p.name} | ${decision(p)} |`);
  return [header, '', '| id | name | decision |', '| --- | --- | --- |', ...table, ''].join('\n');
}

function seasonalSection(places: Place[]): string {
  const rows = places.filter((p) => p.openMonths !== null);
  const table = rows.map(
    (p) => `| ${p.id} | ${p.name} | "${p.seasonalNote}" | ${p.openMonths?.join(', ')} |`
  );
  return [
    '## Seasonal months parsed (only clearly-stated closures; advice text stays verbatim)',
    '',
    `${rows.length} place(s).`,
    '',
    '| id | name | note | open months |',
    '| --- | --- | --- | --- |',
    ...table,
    '',
  ].join('\n');
}

function describeWeekly(p: Place): string {
  if (p.hours.kind !== 'weekly') return p.hours.kind;
  const day = p.hours.weekly.find((d) => d.length > 0);
  if (!day || !day[0]) return 'no intervals';
  return `${formatMinutes(day[0].start)}–${formatMinutes(day[0].end)} daily (inferred)`;
}
